languageCode = 'en-us'
title = 'David Rothera // Links'
theme = 'lynx'
enableEmoji = true

disableKinds = ["taxonomy", "term"]

[author]
name = "David Rothera"
# headline = "Where can you find me"
image = "author.webp"
links = [
    { github = "https://github.com/davidrothera" },
    { instagram = "https://instagram.com/drothera" },
    { twitter = "https://twitter.com/davidrothera" },
    { email = "mailto:hello@rothera.co" },
]
